# Generated by Django 3.0.1 on 2020-01-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pytania',
            options={'verbose_name': 'Pytanie', 'verbose_name_plural': 'Pytania'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Testy'},
        ),
        migrations.AlterModelOptions(
            name='testyuzytkownikow',
            options={'verbose_name': 'TestUzytkownik', 'verbose_name_plural': 'TestyUzytkownicy'},
        ),
        migrations.AlterField(
            model_name='pytania',
            name='odp_czwarta',
            field=models.CharField(max_length=50, verbose_name='Odpowiedz czwarta'),
        ),
        migrations.AlterField(
            model_name='pytania',
            name='odp_druga',
            field=models.CharField(max_length=50, verbose_name='Odpowiedz druga'),
        ),
        migrations.AlterField(
            model_name='pytania',
            name='odp_pierwsza',
            field=models.CharField(max_length=50, verbose_name='Odpowiedz pierwsza'),
        ),
        migrations.AlterField(
            model_name='pytania',
            name='odp_poprawna',
            field=models.IntegerField(verbose_name='Poprawna odpowiedz'),
        ),
        migrations.AlterField(
            model_name='pytania',
            name='odp_trzecia',
            field=models.CharField(max_length=50, verbose_name='Odpowiedz trzecia'),
        ),
        migrations.AlterField(
            model_name='pytania',
            name='pytanie',
            field=models.CharField(max_length=50, verbose_name='Pytanie'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test',
            field=models.CharField(max_length=50, verbose_name='Nazwa testu'),
        ),
    ]
