# Generated by Django 3.0.2 on 2020-01-25 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dzial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzial', models.CharField(max_length=100, verbose_name='Temat')),
            ],
            options={
                'verbose_name': 'Dzial',
                'verbose_name_plural': 'Dzialy',
            },
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoria', models.CharField(max_length=100, verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Temat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temat', models.CharField(max_length=100, verbose_name='Temat')),
                ('plik', models.CharField(max_length=100, verbose_name='Plik')),
                ('dzial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurs.Dzial')),
            ],
            options={
                'verbose_name': 'Temat',
                'verbose_name_plural': 'Tematy',
            },
        ),
        migrations.AddField(
            model_name='dzial',
            name='kategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurs.Kategorie'),
        ),
    ]
